/*
 * openScale
 * Copyright (C) 2026 openScale contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.health.openscale.core.bluetooth.scales

import com.google.common.truth.Truth.assertThat
import com.health.openscale.core.bluetooth.data.ScaleMeasurement
import com.health.openscale.core.bluetooth.data.ScaleUser
import com.health.openscale.core.data.GenderType
import com.health.openscale.core.service.ScannedDeviceInfo
import com.welie.blessed.BluetoothPeripheral
import kotlinx.coroutines.CoroutineScope
import org.junit.Assert.assertThrows
import org.junit.Test
import java.util.Calendar
import java.util.TimeZone
import java.util.UUID
import kotlin.coroutines.EmptyCoroutineContext

/**
 * Unit tests for [HuaweiAhCh100Handler] — the wire-protocol primitives
 * shared by the Huawei AH100 and CH100 body-fat scales.
 *
 * The fixtures encode three realistic measurements and were generated
 * deterministically by `tools/ch100_decoder/_gen_test_fixtures.py` (see the
 * companion repository linked in the PR). The Python helper and the Kotlin
 * code under test are independent re-implementations of the same v2.5.4
 * Java protocol, so a green test here means both ports agree.
 *
 * The test data point at 97.0 kg / 28.0 % matches the values reported by
 * the user in issue #1280 — the same scenario that the broken 3.x master
 * parser turned into 138 kg / 180 % / year 3084.
 */
class HuaweiAhCh100HandlerTest {

    companion object {
        private const val TEST_MAC = "5C:CA:D3:08:7B:4F"
        private const val TEST_USER_ID = 1

        // Generated by _gen_test_fixtures.py with the constants above.
        private const val EXPECTED_AUTH_TOKEN = "11223344551001"
        private const val EXPECTED_MAGIC_KEY  = "4de8e04c2e5f5d2a980fde3456732156"

        // Plaintext = decrypted, post-XOR-de-obfuscation, v2.5.4 layout.
        private const val FIXTURE_USER_PLAINTEXT  = "01ca031801ea070513080c21021c02"
        private const val FIXTURE_LIGHT_PLAINTEXT = "012802bc00ea07010f071e0a04e801"
        private const val FIXTURE_HEAVY_PLAINTEXT = "0104056001ea070301132d00076402"

        // Golden paired frames as sent on the wire. AES-CTR restarts for each
        // block; MAC XOR spans the reconstructed 32-byte plaintext.
        private const val FIXTURE_USER_FRAME1  = "bc200edef702c9bbf2176c755b6eccdd5b92b0"
        private const val FIXTURE_LIGHT_FRAME1 = "bc200ede15036dbaf2176869547ce7dbaf91b0"
        private const val FIXTURE_HEAVY_FRAME1 = "bc200ede3904b1bbf2176a67404fedd82392b0"
        private const val FIXTURE_FRAME2 = "bc208ef8b88e13125f37ece991caaaf8c21f72"

        // Same measurement encrypted for selected app user 7, while the scale
        // record itself still carries its local user id 1.
        private const val HISTORY_FRAME1 = "bc2010d1d404a3c6d3d6bd4bf934a17217136a"
        private const val HISTORY_FRAME2 = "bc2090f79b88796f7ef63dd73390c7578e9ea8"
        private const val INVALID_DATE_HISTORY_FRAME1 = "bc2010d1d404a3c6d3d6b54bf934a17217136a"
        private const val INVALID_DATE_HISTORY_FRAME2 = HISTORY_FRAME2
        val CHAR_RX: UUID = UUID.fromString("0000faa2-0000-1000-8000-00805f9b34fb")
    }

    // -- Primitives ----------------------------------------------------------

    @Test
    fun `obfuscate is self-inverse`() {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val data = hex("DEADBEEFCAFEBABE0102030405060708")
        val once = HuaweiAhCh100Handler.obfuscate(data, mac)
        val twice = HuaweiAhCh100Handler.obfuscate(once, mac)
        assertThat(once).isNotEqualTo(data)
        assertThat(twice).isEqualTo(data)
    }

    @Test
    fun `obfuscate with empty MAC is identity`() {
        val data = hex("DEADBEEF")
        assertThat(HuaweiAhCh100Handler.obfuscate(data, ByteArray(0))).isEqualTo(data)
    }

    @Test
    fun `xorChecksum returns parity byte`() {
        val buf = hex("DEADBEEFCAFE")
        val expected = (0xDE xor 0xAD xor 0xBE xor 0xEF xor 0xCA xor 0xFE).toByte()
        assertThat(HuaweiAhCh100Handler.xorChecksum(buf)).isEqualTo(expected)
    }

    @Test
    fun `buildAuthToken array XORs to zero`() {
        val tok = HuaweiAhCh100Handler.buildAuthToken(TEST_USER_ID)
        assertThat(tok).hasLength(7)
        assertThat(HuaweiAhCh100Handler.xorChecksum(tok)).isEqualTo(0.toByte())
        // First 5 bytes are constants, last byte is the userId.
        assertThat(tok.copyOfRange(0, 5)).isEqualTo(hex("1122334455"))
        assertThat(tok[6].toInt() and 0xFF).isEqualTo(TEST_USER_ID)
    }

    @Test
    fun `buildAuthToken matches reference fixture for userId=1`() {
        val tok = HuaweiAhCh100Handler.buildAuthToken(TEST_USER_ID)
        assertThat(toHex(tok)).isEqualTo(EXPECTED_AUTH_TOKEN)
    }

    @Test
    fun `deriveMagicKey produces 16 bytes matching v2 5 4 layout`() {
        val tok = HuaweiAhCh100Handler.buildAuthToken(TEST_USER_ID)
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val mk = HuaweiAhCh100Handler.deriveMagicKey(tok, mac)
        assertThat(mk).hasLength(16)
        // First 7 bytes = obfuscate(authToken, MAC).
        assertThat(mk.copyOfRange(0, 7)).isEqualTo(HuaweiAhCh100Handler.obfuscate(tok, mac))
        // Last 9 bytes = INITIAL_KEY[7..15].
        assertThat(mk.copyOfRange(7, 16))
            .isEqualTo(HuaweiAhCh100Handler.INITIAL_KEY.copyOfRange(7, 16))
        assertThat(toHex(mk)).isEqualTo(EXPECTED_MAGIC_KEY)
    }

    @Test
    fun `aesCtr is symmetric`() {
        val key = HuaweiAhCh100Handler.hexToBytes(EXPECTED_MAGIC_KEY)
        val pt = hex("01ca031801ea070513080c21021c02")
        val ct = HuaweiAhCh100Handler.aesCtr(pt, key, HuaweiAhCh100Handler.INITIAL_IV)
        val rt = HuaweiAhCh100Handler.aesCtr(ct, key, HuaweiAhCh100Handler.INITIAL_IV)
        assertThat(ct).isNotEqualTo(pt)
        assertThat(rt).isEqualTo(pt)
    }

    // -- Frame writers -------------------------------------------------------

    @Test
    fun `buildPlainCommand writes len plus 1 in the header byte`() {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val payload = hex("11223344")
        val frame = HuaweiAhCh100Handler.buildPlainCommand(
            cmd = HuaweiAhCh100Handler.CMD_AUTH,
            payload = payload,
            mac = mac
        )
        // Wire layout: [0xDB, lengthByte, cmd, ...obfuscated payload...]
        assertThat(frame[0]).isEqualTo(HuaweiAhCh100Handler.FRAME_PLAIN)
        assertThat(frame[1].toInt() and 0xFF).isEqualTo(payload.size + 1)
        assertThat(frame[2]).isEqualTo(HuaweiAhCh100Handler.CMD_AUTH)
        assertThat(frame.copyOfRange(3, frame.size))
            .isEqualTo(HuaweiAhCh100Handler.obfuscate(payload, mac))
    }

    @Test
    fun `buildPlainCommand respects explicit length byte for legacy GET_RECORD`() {
        // openScale v2.5.4 sent GET_RECORD with payload of 8 bytes and a wire
        // lengthByte of 0x07 (it called AHsendCommand(_, _, 0x07-1) which then
        // added 1 in the header).
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val payload = hex("1122334455667788")
        val frame = HuaweiAhCh100Handler.buildPlainCommand(
            cmd = HuaweiAhCh100Handler.CMD_GET_RECORD,
            payload = payload,
            mac = mac,
            explicitLen = 0x07
        )
        assertThat(frame[1].toInt() and 0xFF).isEqualTo(0x07)
        assertThat(frame.size).isEqualTo(3 + payload.size)
    }

    @Test
    fun `buildEncryptedCommand uses payload size as length and AES-CTR encrypts`() {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val mk = HuaweiAhCh100Handler.hexToBytes(EXPECTED_MAGIC_KEY)
        val payload = hex("1122334455667788")
        val frame = HuaweiAhCh100Handler.buildEncryptedCommand(
            cmd = HuaweiAhCh100Handler.CMD_USER_INFO,
            payload = payload,
            magicKey = mk,
            mac = mac
        )
        assertThat(frame[0]).isEqualTo(HuaweiAhCh100Handler.FRAME_ENCRYPTED)
        assertThat(frame[1].toInt() and 0xFF).isEqualTo(payload.size)
        assertThat(frame[2]).isEqualTo(HuaweiAhCh100Handler.CMD_USER_INFO)
        // Recover plaintext: deobfuscate then AES-CTR.
        val deobf = HuaweiAhCh100Handler.obfuscate(frame.copyOfRange(3, frame.size), mac)
        val pt = HuaweiAhCh100Handler.aesCtr(deobf, mk, HuaweiAhCh100Handler.INITIAL_IV)
        assertThat(pt).isEqualTo(payload)
    }

    // -- History lifecycle --------------------------------------------------

    @Test
    fun `history capability starts exact user query once after user-info acknowledgement`() {
        val fixture = Fixture()

        assertThat(fixture.support.implemented).contains(DeviceCapability.HISTORY_READ)
        fixture.authorise()
        fixture.transport.writes.clear()

        fixture.acknowledgeUserInfo()
        fixture.acknowledgeUserInfo()

        assertThat(fixture.transport.writes).hasSize(1)
        assertThat(fixture.transport.writes.single()).isEqualTo(hex("db070b4de8e04c2e595bca"))
    }

    @Test
    fun `history pair publishes for selected user then requests next without fat ack`() {
        val fixture = Fixture()
        fixture.authoriseAndStartHistory()
        fixture.transport.writes.clear()

        fixture.notify(HISTORY_FRAME1)
        assertThat(fixture.published).isEmpty()
        fixture.user.id = 99
        fixture.notify(HISTORY_FRAME2)

        assertThat(fixture.published).hasSize(1)
        assertThat(fixture.published.single().userId).isEqualTo(7)
        assertThat(fixture.published.single().weight).isWithin(1e-4f).of(97.0f)
        assertThat(fixture.transport.writes).hasSize(1)
        assertThat(fixture.transport.writes.single()).isEqualTo(hex("db020b5d"))
    }

    @Test
    fun `bad history timestamp is dropped but still requests next`() {
        val fixture = Fixture()
        fixture.authoriseAndStartHistory()
        fixture.transport.writes.clear()

        fixture.notify(INVALID_DATE_HISTORY_FRAME1)
        fixture.notify(INVALID_DATE_HISTORY_FRAME2)

        assertThat(fixture.published).isEmpty()
        assertThat(fixture.transport.writes).hasSize(1)
        assertThat(fixture.transport.writes.single()).isEqualTo(hex("db020b5d"))
    }

    @Test
    fun `short history pair is not acknowledged`() {
        val fixture = Fixture()
        fixture.authoriseAndStartHistory()
        fixture.transport.writes.clear()

        fixture.notify(HISTORY_FRAME1)
        fixture.notify("bc0090")

        assertThat(fixture.published).isEmpty()
        assertThat(fixture.transport.writes).isEmpty()
    }

    @Test
    fun `live pair publishes and sends only fat-result ack`() {
        val fixture = Fixture()
        fixture.authorise()
        fixture.transport.writes.clear()

        fixture.notify(HISTORY_FRAME1.replace("bc2010", "bc200e"))
        fixture.notify(HISTORY_FRAME2.replace("bc2090", "bc208e"))

        assertThat(fixture.published).hasSize(1)
        assertThat(fixture.published.single().userId).isEqualTo(fixture.user.id)
        assertThat(fixture.transport.writes).hasSize(1)
        assertThat(fixture.transport.writes.single()).isEqualTo(hex("db02135c"))
    }

    @Test
    fun `malformed live pair is not acknowledged`() {
        val fixture = Fixture()
        fixture.authorise()
        fixture.transport.writes.clear()

        fixture.notify(HISTORY_FRAME1.replace("bc2010", "bc200e"))
        fixture.notify("bc008e")

        assertThat(fixture.published).isEmpty()
        assertThat(fixture.transport.writes).isEmpty()
    }

    @Test
    fun `history completion clears a partial pair and reconnect starts a fresh query`() {
        val fixture = Fixture()
        fixture.authoriseAndStartHistory()
        fixture.transport.writes.clear()
        fixture.notify(HISTORY_FRAME1)

        fixture.handler.handleNotification(CHAR_RX, hex("bd0019"))
        fixture.notify(HISTORY_FRAME2)

        assertThat(fixture.published).isEmpty()
        assertThat(fixture.transport.writes).isEmpty()

        fixture.handler.handleDisconnected()
        fixture.authoriseAndStartHistory()
        assertThat(fixture.transport.writes.last()).isEqualTo(hex("db070b4de8e04c2e595bca"))
    }

    // -- Measurement decoding ------------------------------------------------

    @Test
    fun `parseMeasurement decodes user fixture (97 kg, 28 percent)`() {
        val m = HuaweiAhCh100Handler.parseMeasurement(hex(FIXTURE_USER_PLAINTEXT))
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
        assertThat(m.weightKg).isWithin(1e-4f).of(97.0f)
        assertThat(m.fatPct).isWithin(1e-4f).of(28.0f)
        assertThat(m.impedanceOhm).isEqualTo(540)
        assertCalendar(m, year = 2026, monthZeroBased = 4, day = 19, hour = 8, minute = 12, second = 33)
    }

    @Test
    fun `parseMeasurement decodes light fixture`() {
        val m = HuaweiAhCh100Handler.parseMeasurement(hex(FIXTURE_LIGHT_PLAINTEXT))
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
        assertThat(m.weightKg).isWithin(1e-4f).of(55.2f)
        assertThat(m.fatPct).isWithin(1e-4f).of(18.8f)
        assertThat(m.impedanceOhm).isEqualTo(488)
        assertCalendar(m, year = 2026, monthZeroBased = 0, day = 15, hour = 7, minute = 30, second = 10)
    }

    @Test
    fun `parseMeasurement decodes heavy fixture`() {
        val m = HuaweiAhCh100Handler.parseMeasurement(hex(FIXTURE_HEAVY_PLAINTEXT))
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
        assertThat(m.weightKg).isWithin(1e-4f).of(128.4f)
        assertThat(m.fatPct).isWithin(1e-4f).of(35.2f)
        assertThat(m.impedanceOhm).isEqualTo(612)
        assertCalendar(m, year = 2026, monthZeroBased = 2, day = 1, hour = 19, minute = 45, second = 0)
    }

    @Test
    fun `parseMeasurement throws on too-short input`() {
        try {
            HuaweiAhCh100Handler.parseMeasurement(hex("00112233"))
            assertThat(false).isTrue() // not reached
        } catch (e: IllegalArgumentException) {
            assertThat(e.message).contains("at least 15 bytes")
        }
    }

    @Test
    fun `parseMeasurement accepts documented reset-clock year 2000`() {
        val data = hex(FIXTURE_USER_PLAINTEXT).apply {
            this[5] = 0xD0.toByte()
            this[6] = 0x07
        }

        val measurement = HuaweiAhCh100Handler.parseMeasurement(data)

        assertThat(Calendar.getInstance().apply { time = requireNotNull(measurement.dateTime) }.get(Calendar.YEAR))
            .isEqualTo(2000)
    }

    @Test
    fun `parseMeasurement rejects years before reset-clock epoch`() {
        val data = hex(FIXTURE_USER_PLAINTEXT).apply {
            this[5] = 0x01
            this[6] = 0x00
        }

        assertThrows(IllegalArgumentException::class.java) {
            HuaweiAhCh100Handler.parseMeasurement(data)
        }
    }

    // -- End-to-end frame -> measurement -------------------------------------

    @Test
    fun `decodePair round-trips user fixture frames to 97 kg 28 percent`() {
        assertFrameDecodes(
            FIXTURE_USER_FRAME1,
            FIXTURE_FRAME2,
            expectedWeight = 97.0f,
            expectedFat = 28.0f,
            expectedImpedance = 540,
        )
    }

    @Test
    fun `decodePair round-trips light fixture frames to 55_2 kg 18_8 percent`() {
        assertFrameDecodes(
            FIXTURE_LIGHT_FRAME1,
            FIXTURE_FRAME2,
            expectedWeight = 55.2f,
            expectedFat = 18.8f,
            expectedImpedance = 488,
        )
    }

    @Test
    fun `decodePair round-trips heavy fixture frames to 128_4 kg 35_2 percent`() {
        assertFrameDecodes(
            FIXTURE_HEAVY_FRAME1,
            FIXTURE_FRAME2,
            expectedWeight = 128.4f,
            expectedFat = 35.2f,
            expectedImpedance = 612,
        )
    }

    @Test
    fun `regression - merged 32 byte XOR-only buffer would NOT match (broken 3x)`() {
        // This test pins down the regression we are fixing: the broken 3.x
        // master parser would compute (1457 - byte[1]) / 10 on the raw
        // deobfuscated buffer, which deliberately *does not* equal 97.0.
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val frame = hex(FIXTURE_USER_FRAME1)
        val deobfTail = HuaweiAhCh100Handler.deobfuscateTail(frame, mac)
        val brokenWeight = (1457 - (deobfTail[1].toInt() and 0xFF)) / 10.0f
        assertThat(brokenWeight).isNotWithin(1e-4f).of(97.0f)
    }

    // -- Helpers -------------------------------------------------------------

    private fun assertFrameDecodes(
        firstFrameHex: String,
        secondFrameHex: String,
        expectedWeight: Float,
        expectedFat: Float,
        expectedImpedance: Int,
    ) {
        val mac = HuaweiAhCh100Handler.macStringToBytes(TEST_MAC)
        val mk = HuaweiAhCh100Handler.hexToBytes(EXPECTED_MAGIC_KEY)
        val m = HuaweiAhCh100Handler.decodePair(hex(firstFrameHex), hex(secondFrameHex), mk, mac)
        assertThat(m.weightKg).isWithin(1e-4f).of(expectedWeight)
        assertThat(m.fatPct).isWithin(1e-4f).of(expectedFat)
        assertThat(m.impedanceOhm).isEqualTo(expectedImpedance)
        assertThat(m.userId).isEqualTo(TEST_USER_ID)
    }

    private fun assertCalendar(
        m: HuaweiAhCh100Handler.Measurement,
        year: Int, monthZeroBased: Int, day: Int, hour: Int, minute: Int, second: Int
    ) {
        val dt = m.dateTime
        assertThat(dt).isNotNull()
        // The protocol object uses the system default timezone via
        // Calendar.getInstance(); we read fields back the same way to make
        // the assertion timezone-independent.
        val cal = Calendar.getInstance().apply { time = dt!! }
        assertThat(cal.get(Calendar.YEAR)).isEqualTo(year)
        assertThat(cal.get(Calendar.MONTH)).isEqualTo(monthZeroBased)
        assertThat(cal.get(Calendar.DAY_OF_MONTH)).isEqualTo(day)
        assertThat(cal.get(Calendar.HOUR_OF_DAY)).isEqualTo(hour)
        assertThat(cal.get(Calendar.MINUTE)).isEqualTo(minute)
        assertThat(cal.get(Calendar.SECOND)).isEqualTo(second)
    }

    private fun hex(s: String): ByteArray = HuaweiAhCh100Handler.hexToBytes(s)
    private fun toHex(b: ByteArray): String = b.joinToString("") { "%02x".format(it.toInt() and 0xFF) }

    private class Fixture {
        val published = mutableListOf<ScaleMeasurement>()
        val user = ScaleUser(
            id = 7,
            birthday = Calendar.getInstance().apply { set(1991, Calendar.JANUARY, 2) }.time,
            bodyHeight = 180f,
            gender = GenderType.MALE,
            initialWeight = 75f
        )
        val handler = HuaweiAhCh100Handler()
        val transport = CapturingTransport()
        val support = requireNotNull(
            handler.supportFor(
                ScannedDeviceInfo(
                    name = "AH100",
                    address = TEST_MAC,
                    rssi = -50,
                    serviceUuids = emptyList(),
                    manufacturerData = null
                )
            )
        )

        init {
            handler.attach(
                transport = transport,
                callbacks = object : ScaleDeviceHandler.Callbacks {
                    override fun onPublish(measurement: ScaleMeasurement) {
                        published += measurement
                    }

                    override fun resolveString(resId: Int, vararg args: Any) = "res:$resId"
                },
                settings = object : ScaleDeviceHandler.DriverSettings {
                    override fun getInt(key: String, default: Int) = default
                    override fun putInt(key: String, value: Int) = Unit
                    override fun getString(key: String, default: String?) = default
                    override fun putString(key: String, value: String) = Unit
                    override fun remove(key: String) = Unit
                },
                data = object : ScaleDeviceHandler.DataProvider {
                    override fun currentUser() = user
                    override fun usersForDevice() = listOf(user)
                    override fun lastMeasurementFor(userId: Int): ScaleMeasurement? = null
                },
                scope = CoroutineScope(EmptyCoroutineContext)
            )
        }

        fun authorise() {
            handler.handleConnected(user)
            handler.handleNotification(CHAR_RX, HuaweiAhCh100Handler.hexToBytes("bd0000"))
            handler.handleNotification(CHAR_RX, HuaweiAhCh100Handler.hexToBytes("bd01265d"))
        }

        fun acknowledgeUserInfo() {
            handler.handleNotification(CHAR_RX, HuaweiAhCh100Handler.hexToBytes("bd0020"))
        }

        fun authoriseAndStartHistory() {
            authorise()
            acknowledgeUserInfo()
        }

        fun notify(frame: String) {
            handler.handleNotification(CHAR_RX, HuaweiAhCh100Handler.hexToBytes(frame))
        }
    }

    private class CapturingTransport : ScaleDeviceHandler.Transport {
        val writes = mutableListOf<ByteArray>()

        override fun setNotifyOn(service: UUID, characteristic: UUID) = Unit
        override fun write(service: UUID, characteristic: UUID, payload: ByteArray, withResponse: Boolean) {
            writes += payload
        }

        override fun read(service: UUID, characteristic: UUID) = Unit
        override fun disconnect() = Unit
        override fun getPeripheral(): BluetoothPeripheral? = null
        override fun hasCharacteristic(service: UUID, characteristic: UUID) = true
    }
}
